#############################################################################
# Makefile for building: satori
# Generated by qmake (2.00a) (Qt 4.0.0) on: Mon Jan  2 02:00:29 2006
# Project:  satori.pro
# Template: subdirs
# Command: /usr/qt/4/bin/qmake -o Makefile satori.pro
#############################################################################

first: make_first
MAKEFILE      = Makefile
QMAKE         = /usr/qt/4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src-satori \
		sub-src-modules-arch-avr \
		sub-src-modules-comm-serial \
		sub-src-monitor

src/satori/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/satori/" || $(MKDIR) "src/satori/"
	cd src/satori && $(QMAKE) satori.pro
sub-src-satori-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) "src/satori/" || $(MKDIR) "src/satori/"
	cd src/satori && $(QMAKE) satori.pro
sub-src-satori: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE)
sub-src-satori-make_first: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE) first
sub-src-satori-all: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE) all
sub-src-satori-clean: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE) clean
sub-src-satori-distclean: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE) distclean
sub-src-satori-install_subtargets: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE) install
sub-src-satori-uninstall_subtargets: src/satori/$(MAKEFILE) FORCE
	cd src/satori && $(MAKE) uninstall
src/modules/arch/avr/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/modules/arch/avr/" || $(MKDIR) "src/modules/arch/avr/"
	cd src/modules/arch/avr && $(QMAKE) avr.pro
sub-src-modules-arch-avr-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) "src/modules/arch/avr/" || $(MKDIR) "src/modules/arch/avr/"
	cd src/modules/arch/avr && $(QMAKE) avr.pro
sub-src-modules-arch-avr: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE)
sub-src-modules-arch-avr-make_first: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE) first
sub-src-modules-arch-avr-all: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE) all
sub-src-modules-arch-avr-clean: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE) clean
sub-src-modules-arch-avr-distclean: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE) distclean
sub-src-modules-arch-avr-install_subtargets: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE) install
sub-src-modules-arch-avr-uninstall_subtargets: src/modules/arch/avr/$(MAKEFILE) FORCE
	cd src/modules/arch/avr && $(MAKE) uninstall
src/modules/comm/serial/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/modules/comm/serial/" || $(MKDIR) "src/modules/comm/serial/"
	cd src/modules/comm/serial && $(QMAKE) serial.pro
sub-src-modules-comm-serial-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) "src/modules/comm/serial/" || $(MKDIR) "src/modules/comm/serial/"
	cd src/modules/comm/serial && $(QMAKE) serial.pro
sub-src-modules-comm-serial: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE)
sub-src-modules-comm-serial-make_first: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE) first
sub-src-modules-comm-serial-all: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE) all
sub-src-modules-comm-serial-clean: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE) clean
sub-src-modules-comm-serial-distclean: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE) distclean
sub-src-modules-comm-serial-install_subtargets: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE) install
sub-src-modules-comm-serial-uninstall_subtargets: src/modules/comm/serial/$(MAKEFILE) FORCE
	cd src/modules/comm/serial && $(MAKE) uninstall
src/monitor/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/monitor/" || $(MKDIR) "src/monitor/"
	cd src/monitor && $(QMAKE) monitor.pro
sub-src-monitor-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) "src/monitor/" || $(MKDIR) "src/monitor/"
	cd src/monitor && $(QMAKE) monitor.pro
sub-src-monitor: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE)
sub-src-monitor-make_first: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE) first
sub-src-monitor-all: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE) all
sub-src-monitor-clean: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE) clean
sub-src-monitor-distclean: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE) distclean
sub-src-monitor-install_subtargets: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE) install
sub-src-monitor-uninstall_subtargets: src/monitor/$(MAKEFILE) FORCE
	cd src/monitor && $(MAKE) uninstall

Makefile: satori.pro  /usr/qt/4/mkspecs/linux-g++/qmake.conf /usr/qt/4/mkspecs/qconfig.pri \
		/usr/qt/4/mkspecs/features/qt_config.prf \
		/usr/qt/4/mkspecs/features/exclusive_builds.prf \
		/usr/qt/4/mkspecs/features/default_pre.prf \
		/usr/qt/4/mkspecs/features/debug.prf \
		/usr/qt/4/mkspecs/features/default_post.prf \
		/usr/qt/4/mkspecs/features/warn_on.prf \
		/usr/qt/4/mkspecs/features/qt.prf \
		/usr/qt/4/mkspecs/features/unix/thread.prf \
		/usr/qt/4/mkspecs/features/moc.prf \
		/usr/qt/4/mkspecs/features/resources.prf \
		/usr/qt/4/mkspecs/features/uic.prf
	$(QMAKE) -o Makefile satori.pro
/usr/qt/4/mkspecs/qconfig.pri:
/usr/qt/4/mkspecs/features/qt_config.prf:
/usr/qt/4/mkspecs/features/exclusive_builds.prf:
/usr/qt/4/mkspecs/features/default_pre.prf:
/usr/qt/4/mkspecs/features/debug.prf:
/usr/qt/4/mkspecs/features/default_post.prf:
/usr/qt/4/mkspecs/features/warn_on.prf:
/usr/qt/4/mkspecs/features/qt.prf:
/usr/qt/4/mkspecs/features/unix/thread.prf:
/usr/qt/4/mkspecs/features/moc.prf:
/usr/qt/4/mkspecs/features/resources.prf:
/usr/qt/4/mkspecs/features/uic.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile satori.pro

qmake_all: sub-src-satori-qmake_all sub-src-modules-arch-avr-qmake_all sub-src-modules-comm-serial-qmake_all sub-src-monitor-qmake_all FORCE

make_first: sub-src-satori-make_first sub-src-modules-arch-avr-make_first sub-src-modules-comm-serial-make_first sub-src-monitor-make_first FORCE
all: sub-src-satori-all sub-src-modules-arch-avr-all sub-src-modules-comm-serial-all sub-src-monitor-all FORCE
clean: sub-src-satori-clean sub-src-modules-arch-avr-clean sub-src-modules-comm-serial-clean sub-src-monitor-clean FORCE
distclean: sub-src-satori-distclean sub-src-modules-arch-avr-distclean sub-src-modules-comm-serial-distclean sub-src-monitor-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-satori-install_subtargets sub-src-modules-arch-avr-install_subtargets sub-src-modules-comm-serial-install_subtargets sub-src-monitor-install_subtargets FORCE
uninstall_subtargets: sub-src-satori-uninstall_subtargets sub-src-modules-arch-avr-uninstall_subtargets sub-src-modules-comm-serial-uninstall_subtargets sub-src-monitor-uninstall_subtargets FORCE

/usr/qt/4/bin/moc:
	(cd "$(QTDIR)/src/tools/moc" && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

